# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-telemetry
  description: GitHub Action for telemetry harvesting from repos
  homepage: https://cloudposse.com/accelerate
  topics: ""
